### PR TITLE
fix null in tool type response

### PR DESCRIPTION
**Pull request by wseaton**
The tool calling response was incorrectly returning a null for function type which breaks langchain's tools handling: 

```
{'id': '9',
 'choices': [{'finish_reason': 'stop',
   'index': 0,
   'message': {'content': None,
    'role': 'assistant',
    'tool_calls': [{'id': 'call-202d73de-9231-4168-91c1-710cf6fbfd75',
      'type': None,
      'function': {'name': 'compute_square', 'arguments': '{"number":212}'}}]},
   'logprobs': None}],
 'created': 1723724369,
 'model': '/mnt/models/',
 'system_fingerprint': 'local',
 'object': 'chat.completion',
 'usage': {'completion_tokens': 23,
  'prompt_tokens': 74,
  'total_tokens': 97,
  'avg_tok_per_sec': 120.04951,
  'avg_prompt_tok_per_sec': 1396.2264,
  'avg_compl_tok_per_sec': 30.463577,
  'total_time_sec': 0.808,
  'total_prompt_time_sec': 0.053,
  'total_completion_time_sec': 0.755}}
```

The patch fixes this to return `"type": "function"`

### CODE REVIEW

**Comment by EricLBuehler** [comment]
@wseaton let me know when this is ready for review!

**Comment by wseaton** [comment]
Building my fork now and should be integration testing it shortly!

**Comment by wseaton** [comment]
Building my fork now and should be integration testing it shortly!

**Comment by wseaton** [comment]
Yep, the above patch works, new inference output: 

Request
```
{
  "model": "/mnt/models/",
  "messages": [
    {
      "role": "user",
      "content": "What is the square of 212?"
    }
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "compute_square",
        "description": "Computes the square of a number.",
        "parameters": {
          "type": "object",
          "properties": {
            "number": {
              "type": "integer"
            }
          },
          "required": [
            "number"
          ]
        }
      }
    }
  ],
  "tool_choice": "auto"
}
```

Response
```
{
  "id": "1",
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": null,
        "role": "assistant",
        "tool_calls": [
          {
            "id": "call-7519495d-a7aa-47bb-b577-9121be4d0900",
            "type": "function",
            "function": {
              "name": "compute_square",
              "arguments": "{\"number\":212}"
            }
          }
        ]
      },
      "logprobs": null
    }
  ],
  "created": 1723734130,
  "model": "/mnt/models/",
  "system_fingerprint": "local",
  "object": "chat.completion",
  "usage": {
    "completion_tokens": 23,
    "prompt_tokens": 74,
    "total_tokens": 97,
    "avg_tok_per_sec": 120.04951,
    "avg_prompt_tok_per_sec": 1396.2264,
    "avg_compl_tok_per_sec": 30.463577,
    "total_time_sec": 0.808,
    "total_prompt_time_sec": 0.053,
    "total_completion_time_sec": 0.755
  }
}
```

I think this is ready to merge

**Review by EricLBuehler — APPROVED** [review]
Looks good, thanks for the fix!

**Pull request merged**
