### PR TITLE
Support for EXL2 format (WIP)

### PR DESCRIPTION
**Pull request by ro99**
This is a draft PR to start adding support to the ExllamaV2 format.

### CODE REVIEW

**Comment by ro99** [comment]
@EricLBuehler can you create a new branch for this? Thank you.

**Comment by EricLBuehler** [comment]
Hi @ro99 sorry, perhaps I don't understand. What did you mean by creating a new branch?

I can merge the PR on the Candle fork if that helps. This code looks great so far, please let me know when I should review!

**Comment by ro99** [comment]
Hello @EricLBuehler I was thinking on working on this on a separate [branch](https://github.com/EricLBuehler/mistral.rs/branches). For now this is just a WIP and I did not want to merge in the master. Please let me know if this is not the correct approach.

**Comment by EricLBuehler** [comment]
Hi @ro99 sorry for any confusion - what I had in mind was the following:
1) Gor you to develop the changes on this draft PR (so on the branch for your fork).
2) Then, when you think it is ready (we can always add ISQ support and polish it later), you could mark the PR as "Ready for review" and we can finalize it!

I was wondering if this workflow would work for you?

**Comment by ro99** [comment]
Yes, this makes sense, I will follow with this approach then 😄

**Comment by EricLBuehler** [comment]
@ro99 that sounds great! I merged your PR on the Candle fork.

**Comment by ro99** [comment]
Sorry, something else showed up, I think I will not have much time to look into this now 😕

**Pull request closed without merging**
