### PR TITLE
Update Metal, CUDA Candle impls and ISQ

### PR DESCRIPTION
**Pull request by EricLBuehler**
Metal: MLX
CUDA: PaddedData for quantized

@ChristianWeyer could you please test if this builds on Metal?

### CODE REVIEW

**Comment by EricLBuehler** [comment]
Hi @ChristianWeyer thanks for testing it! I pushed some changes which should hopefully fix this, can you please test it again?

**Comment by ChristianWeyer** [comment]
> Hi @ChristianWeyer thanks for testing it! I pushed some changes which should hopefully fix this, can you please test it again?
> 
> I made some changes to things which will affect the UQFF backend - could you also please quickly test that:
> 
> ```
> cargo run --features metal --release -- -i --isq Q4K plain -m microsoft/Phi-3.5-mini-instruct --write-uqff test.uqff
> ```

Here we go:
```
error[E0308]: mismatched types
   --> /Users/christianweyer/.cargo/git/checkouts/candle-c6a149c3b35a488f/c04861d/candle-core/src/quantized/metal.rs:223:39
    |
223 |         Ok(read_to_vec::<u8>(&buffer, self.buffer.length()))
    |            -----------------          ^^^^^^^^^^^^^^^^^^^^ expected `usize`, found `u64`
    |            |
    |            arguments to this function are incorrect
    |
note: function defined here
   --> /Users/christianweyer/.cargo/git/checkouts/candle-c6a149c3b35a488f/c04861d/candle-core/src/quantized/metal.rs:240:4
    |
240 | fn read_to_vec<T: Clone>(buffer: &Buffer, n: usize) -> Vec<T> {
    |    ^^^^^^^^^^^                            --------
help: you can convert a `u64` to a `usize` and panic if the converted value doesn't fit
    |
223 |         Ok(read_to_vec::<u8>(&buffer, self.buffer.length().try_into().unwrap()))
    |                                                           ++++++++++++++++++++

   Compiling rustls-webpki v0.102.8
For more information about this error, try `rustc --explain E0308`.
error: could not compile `candle-core` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by EricLBuehler** [comment]
@ChristianWeyer thanks, I added a quick cast - could you please try it again?

**Comment by ChristianWeyer** [comment]
```
warning: variable does not need to be mutable
   --> mistralrs-core/src/pipeline/isq.rs:144:18
    |
144 |             let (mut tensors, mapper) = match organization {
    |                  ----^^^^^^^
    |                  |
    |                  help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default

error[E0382]: borrow of moved value: `tensors`
    --> mistralrs-core/src/pipeline/isq.rs:401:25
     |
144  |               let (mut tensors, mapper) = match organization {
     |                    ----------- move occurs because `tensors` has type `Vec<(&mut Arc<dyn QuantMethod>, std::option::Option<usize>)>`, which does not implement the `Copy` trait
...
342  |                       tensors.into_iter().zip(devices_and_dtypes).for_each(
     |                               ----------- `tensors` moved due to this method call
...
353  |                           .into_iter()
     |                            ----------- `tensors` moved due to this method call
...
401  | /                         tensors
402  | |                             .iter()
     | |___________________________________^ value borrowed here after move
     |
note: `std::iter::IntoIterator::into_iter` takes ownership of the receiver `self`, which moves `tensors`
    --> /Users/christianweyer/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/iter/traits/collect.rs:346:18
     |
346  |     fn into_iter(self) -> Self::IntoIter;
     |                  ^^^^
     = note: borrow occurs due to deref coercion to `[(&mut Arc<dyn QuantMethod>, std::option::Option<usize>)]`
note: deref defined here
    --> /Users/christianweyer/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2818:5
     |
2818 |     type Target = [T];
     |     ^^^^^^^^^^^
help: you could `clone` the value and consume it, if the `&mut Arc<dyn QuantMethod>: Clone` trait bound could be satisfied
     |
352  |                     tensors.clone()
     |                            ++++++++
help: you could `clone` the value and consume it, if the `&mut Arc<dyn QuantMethod>: Clone` trait bound could be satisfied
     |
342  |                     tensors.clone().into_iter().zip(devices_and_dtypes).for_each(
     |                            ++++++++

For more information about this error, try `rustc --explain E0382`.
warning: `mistralrs-core` (lib) generated 1 warning
error: could not compile `mistralrs-core` (lib) due to 1 previous error; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
```

**Comment by EricLBuehler** [comment]
@ChristianWeyer I think this should compile now, can you please test it :)?

Also, please, the UQFF:
```
cargo run --features metal --release -- -i --isq Q4K plain -m microsoft/Phi-3.5-mini-instruct --write-uqff test.uqff
```
And then:
```
cargo run --features metal --release -- -i --isq Q4K plain -m microsoft/Phi-3.5-mini-instruct --from-uqff test.uqff
```
Thanks!

**Comment by ChristianWeyer** [comment]
```
❯ cargo run --features metal --release -- -i --isq Q4K plain -m microsoft/Phi-3.5-mini-instruct --write-uqff test.uqff
   Compiling mistralrs-core v0.3.1 (/Users/christianweyer/Sources/mistral.rs/mistralrs-core)
error[E0308]: mismatched types
   --> mistralrs-core/src/pipeline/isq.rs:344:39
    |
344 |   ...                   *tensor = tensor
    |  _______________________-------___^
    | |                       |
    | |                       expected due to the type of this binding
345 | | ...                       .clone()
346 | | ...                       .apply_isq(dtype, device.clone(), &n_quantized)
347 | | ...                       .unwrap();
    | |___________________________________^ expected `&mut Arc<dyn QuantMethod>`, found `Arc<dyn QuantMethod>`
    |
    = note: expected mutable reference `&mut Arc<(dyn QuantMethod + 'static)>`
                          found struct `Arc<dyn QuantMethod>`
help: consider dereferencing here to assign to the mutably borrowed value
    |
344 |                             **tensor = tensor
    |                             +

error[E0308]: mismatched types
   --> mistralrs-core/src/pipeline/isq.rs:357:39
    |
357 |   ...                   *tensor = tensor
    |  _______________________-------___^
    | |                       |
    | |                       expected due to the type of this binding
358 | | ...                       .clone()
359 | | ...                       .apply_isq(dtype, device.clone(), &n_quantized)
360 | | ...                       .unwrap();
    | |___________________________________^ expected `&mut Arc<dyn QuantMethod>`, found `Arc<dyn QuantMethod>`
    |
    = note: expected mutable reference `&mut Arc<(dyn QuantMethod + 'static)>`
                          found struct `Arc<dyn QuantMethod>`
help: consider dereferencing here to assign to the mutably borrowed value
    |
357 |                             **tensor = tensor
    |                             +

For more information about this error, try `rustc --explain E0308`.
error: could not compile `mistralrs-core` (lib) due to 2 previous errors
```

**Comment by EricLBuehler** [comment]
@ChristianWeyer alright - *now* it should compile :)

**Comment by ChristianWeyer** [comment]
```
❯ cargo run --features metal --release -- -i --isq Q4K plain -m microsoft/Phi-3.5-mini-instruct --write-uqff test.uqff
   Compiling mistralrs-core v0.3.1 (/Users/christianweyer/Sources/mistral.rs/mistralrs-core)
error[E0594]: cannot assign to `**tensor`, which is behind a `&` reference
   --> mistralrs-core/src/pipeline/isq.rs:357:29
    |
357 | ...                   **tensor = tensor
    |                       ^^^^^^^^ `tensor` is a `&` reference, so the data it refers to cannot be written
    |
help: you may want to use `iter_mut` here
    |
353 |                         .iter_mut()
    |                          ~~~~~~~~

error[E0507]: cannot move out of a shared reference
   --> mistralrs-core/src/pipeline/isq.rs:357:40
    |
357 |   ...                   **tensor = tensor
    |  __________________________________^
358 | | ...                       .clone()
    | |__________________________________^ move occurs because value has type `Arc<dyn QuantMethod>`, which does not implement the `Copy` trait

Some errors have detailed explanations: E0507, E0594.
For more information about an error, try `rustc --explain E0507`.
error: could not compile `mistralrs-core` (lib) due to 2 previous errors
```

**Comment by EricLBuehler** [comment]
@ChristianWeyer thanks for the quick feedback - I fixed that now I think :)

**Comment by ChristianWeyer** [comment]
First one:

```
❯ cargo run --features metal --release -- -i --isq Q4K plain -m microsoft/Phi-3.5-mini-instruct --write-uqff test.uqff
   Compiling mistralrs-core v0.3.1 (/Users/christianweyer/Sources/mistral.rs/mistralrs-core)
   Compiling mistralrs-server v0.3.1 (/Users/christianweyer/Sources/mistral.rs/mistralrs-server)
    Finished `release` profile [optimized] target(s) in 23.25s
     Running `target/release/mistralrs-server -i --isq Q4K plain -m microsoft/Phi-3.5-mini-instruct --write-uqff test.uqff`
2024-10-02T18:20:02.593514Z  INFO mistralrs_server: avx: false, neon: true, simd128: false, f16c: false
2024-10-02T18:20:02.593558Z  INFO mistralrs_server: Sampling method: penalties -> temperature -> topk -> topp -> minp -> multinomial
2024-10-02T18:20:02.593612Z  INFO mistralrs_server: Model kind is: normal (no quant, no adapters)
2024-10-02T18:20:02.595027Z  INFO mistralrs_core::pipeline::normal: Loading `tokenizer.json` at `microsoft/Phi-3.5-mini-instruct`
tokenizer.json [00:00:00] [████████████████████████████████████████████████████████] 1.76 MiB/1.76 MiB 2.44 MiB/s (0s)2024-10-02T18:20:03.723070Z  INFO mistralrs_core::pipeline::normal: Loading `config.json` at `microsoft/Phi-3.5-mini-instruct`
config.json [00:00:00] [███████████████████████████████████████████████████████████] 3.37 KiB/3.37 KiB 8.16 KiB/s (0s)2024-10-02T18:20:04.946563Z  INFO mistralrs_core::pipeline::paths: Found model weight filenames ["model-00001-of-00002.safetensors", "model-00002-of-00002.safetensors"]
..del-00001-of-00002.safetensors [00:09:36] [█████████████████████████████████████████████████████████████████████████████████████████████████████] 4.63 GiB/4.63 GiB 8.23 MiB/s (0s)..del-00002-of-00002.safetensors [00:12:42] [█████████████████████████████████████████████████████████████████████████████████████████████████████] 2.49 GiB/2.49 GiB 3.34 MiB/s (0s)2024-10-02T18:42:25.612880Z  INFO mistralrs_core::pipeline::normal: Loading `generation_config.json` at `microsoft/Phi-3.5-mini-instruct`
generation_config.json [00:00:00] [████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████] 195 B/195 B 590 B/s (0s)2024-10-02T18:42:26.413583Z  INFO mistralrs_core::pipeline::normal: Loading `tokenizer_config.json` at `microsoft/Phi-3.5-mini-instruct`
tokenizer_config.json [00:00:00] [███████████████████████████████████████████████████████████████████████████████████████████████████████████████] 3.89 KiB/3.89 KiB 29.25 KiB/s (0s)2024-10-02T18:42:26.793515Z  INFO mistralrs_core::pipeline::normal: Loading model `microsoft/Phi-3.5-mini-instruct` on metal[4294968411].
2024-10-02T18:42:26.793891Z  INFO mistralrs_core::utils::log: Automatic loader type determined to be `phi3`
2024-10-02T18:42:27.654132Z  INFO mistralrs_core::utils::normal: DType selected is BF16.
2024-10-02T18:42:27.654197Z  INFO mistralrs_core::pipeline::normal: Model config: Config { vocab_size: 32064, hidden_act: Silu, hidden_size: 3072, intermediate_size: 8192, num_hidden_layers: 32, num_attention_heads: 32, num_key_value_heads: 32, rms_norm_eps: 1e-5, rope_theta: 10000.0, bos_token_id: Some(1), eos_token_id: Some(32000), rope_scaling: Some(Classic { short_factor: [1.0, 1.0199999809265137, 1.0299999713897705, 1.0299999713897705, 1.0499999523162842, 1.0499999523162842, 1.0499999523162842, 1.0499999523162842, 1.0499999523162842, 1.069999933242798, 1.0999999046325684, 1.1099998950958252, 1.1599998474121094, 1.1599998474121094, 1.1699998378753662, 1.2899998426437378, 1.339999794960022, 1.679999828338623, 1.7899998426437378, 1.8199998140335083, 1.8499997854232788, 1.879999756813049, 1.90999972820282, 1.9399996995925903, 1.9899996519088743, 2.0199997425079346, 2.0199997425079346, 2.0199997425079346, 2.0199997425079346, 2.0199997425079346, 2.0199997425079346, 2.0299997329711914, 2.0299997329711914, 2.0299997329711914, 2.0299997329711914, 2.0299997329711914, 2.0299997329711914, 2.0299997329711914, 2.0299997329711914, 2.0299997329711914, 2.0799996852874756, 2.0899996757507324, 2.189999580383301, 2.2199995517730713, 2.5899994373321533, 2.729999542236328, 2.749999523162842, 2.8399994373321533], long_factor: [1.0800000429153442, 1.1100000143051147, 1.1399999856948853, 1.340000033378601, 1.5899999141693115, 1.600000023841858, 1.6200000047683716, 2.620000123977661, 3.2300000190734863, 3.2300000190734863, 4.789999961853027, 7.400000095367432, 7.700000286102295, 9.09000015258789, 12.199999809265137, 17.670000076293945, 24.46000099182129, 28.57000160217285, 30.420001983642575, 30.840002059936523, 32.590003967285156, 32.93000411987305, 42.32000350952149, 44.96000289916992, 50.34000396728515, 50.45000457763672, 57.55000305175781, 57.93000411987305, 58.21000289916992, 60.1400032043457, 62.61000442504883, 62.62000274658203, 62.71000289916992, 63.1400032043457, 63.1400032043457, 63.77000427246094, 63.93000411987305, 63.96000289916992, 63.970001220703125, 64.02999877929688, 64.06999969482422, 64.08000183105469, 64.12000274658203, 64.41000366210938, 64.4800033569336, 64.51000213623047, 64.52999877929688, 64.83999633789063], scaling_type: Su }), max_position_embeddings: 131072, use_flash_attn: false, sliding_window: Some(262144), original_max_position_embeddings: 4096, quantization_config: None, tie_word_embeddings: false }
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 128/128 [00:00<00:00, 265.93it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 67/67 [00:00<00:00, 184.21it/s]
2024-10-02T18:42:29.125913Z  INFO mistralrs_core::pipeline::isq: Applying in-situ quantization into Some(Q4K) to 129 tensors.
2024-10-02T18:43:07.943909Z  INFO mistralrs_core::pipeline::isq: Serializing 129 ISQ tensors to `test.uqff`.
2024-10-02T18:43:55.827583Z  INFO mistralrs_core::pipeline::isq: Applied in-situ quantization into Some(Q4K) to 129 tensors out of 129 total tensors. Took 86.69s
2024-10-02T18:43:55.856311Z  INFO mistralrs_core::pipeline::chat_template: bos_toks = "<s>", eos_toks = "<|endoftext|>", "<|end|>", "<|assistant|>", unk_tok = <unk>
2024-10-02T18:43:55.858868Z  INFO mistralrs_server: Model loaded.
2024-10-02T18:43:55.858954Z  INFO mistralrs_server::interactive_mode: Starting interactive loop with sampling params: SamplingParams { temperature: Some(0.1), top_k: Some(32), top_p: Some(0.1), min_p: Some(0.05), top_n_logprobs: 0, frequency_penalty: Some(0.1), presence_penalty: Some(0.1), stop_toks: None, max_len: Some(4096), logits_bias: None, n_choices: 1, dry_params: Some(DrySamplingParams { sequence_breakers: ["\n", ":", "\"", "*"], multiplier: 0.0, base: 1.75, allowed_length: 2 }) }
====================
Welcome to interactive mode! Because this model is a text model, you can enter prompts and chat with the model.

Commands:
- `\help`: Display this message.
- `\exit`: Quit interactive mode.
- `\system <system message here>`:
    Add a system message to the chat without running the model.
    Ex: `\system Always respond as a pirate.`
====================
> hi
Hello! How can I help you today?
>
```

**Comment by ChristianWeyer** [comment]
Second one:

```
❯ cargo run --features metal --release -- -i --isq Q4K plain -m microsoft/Phi-3.5-mini-instruct --from-uqff test.uqff
    Finished `release` profile [optimized] target(s) in 0.64s
     Running `target/release/mistralrs-server -i --isq Q4K plain -m microsoft/Phi-3.5-mini-instruct --from-uqff test.uqff`
2024-10-02T18:49:59.865669Z  INFO mistralrs_server: avx: false, neon: true, simd128: false, f16c: false
2024-10-02T18:49:59.865714Z  INFO mistralrs_server: Sampling method: penalties -> temperature -> topk -> topp -> minp -> multinomial
2024-10-02T18:49:59.865761Z  INFO mistralrs_server: Model kind is: normal (no quant, no adapters)
2024-10-02T18:49:59.866681Z  INFO mistralrs_core::pipeline::normal: Loading `tokenizer.json` at `microsoft/Phi-3.5-mini-instruct`
2024-10-02T18:49:59.866736Z  INFO mistralrs_core::pipeline::normal: Loading `config.json` at `microsoft/Phi-3.5-mini-instruct`
2024-10-02T18:50:00.266494Z  INFO mistralrs_core::pipeline::paths: Found model weight filenames ["model-00001-of-00002.safetensors", "model-00002-of-00002.safetensors"]
2024-10-02T18:50:00.630534Z  INFO mistralrs_core::pipeline::normal: Loading `generation_config.json` at `microsoft/Phi-3.5-mini-instruct`
2024-10-02T18:50:01.170093Z  INFO mistralrs_core::pipeline::normal: Loading `tokenizer_config.json` at `microsoft/Phi-3.5-mini-instruct`
2024-10-02T18:50:01.170625Z  INFO mistralrs_core::pipeline::normal: Loading model `microsoft/Phi-3.5-mini-instruct` on metal[4294968411].
2024-10-02T18:50:01.170819Z  INFO mistralrs_core::utils::log: Automatic loader type determined to be `phi3`
2024-10-02T18:50:01.176142Z  INFO mistralrs_core::utils::normal: DType selected is BF16.
2024-10-02T18:50:01.176212Z  INFO mistralrs_core::pipeline::normal: Model config: Config { vocab_size: 32064, hidden_act: Silu, hidden_size: 3072, intermediate_size: 8192, num_hidden_layers: 32, num_attention_heads: 32, num_key_value_heads: 32, rms_norm_eps: 1e-5, rope_theta: 10000.0, bos_token_id: Some(1), eos_token_id: Some(32000), rope_scaling: Some(Classic { short_factor: [1.0, 1.0199999809265137, 1.0299999713897705, 1.0299999713897705, 1.0499999523162842, 1.0499999523162842, 1.0499999523162842, 1.0499999523162842, 1.0499999523162842, 1.069999933242798, 1.0999999046325684, 1.1099998950958252, 1.1599998474121094, 1.1599998474121094, 1.1699998378753662, 1.2899998426437378, 1.339999794960022, 1.679999828338623, 1.7899998426437378, 1.8199998140335083, 1.8499997854232788, 1.879999756813049, 1.90999972820282, 1.9399996995925903, 1.9899996519088743, 2.0199997425079346, 2.0199997425079346, 2.0199997425079346, 2.0199997425079346, 2.0199997425079346, 2.0199997425079346, 2.0299997329711914, 2.0299997329711914, 2.0299997329711914, 2.0299997329711914, 2.0299997329711914, 2.0299997329711914, 2.0299997329711914, 2.0299997329711914, 2.0299997329711914, 2.0799996852874756, 2.0899996757507324, 2.189999580383301, 2.2199995517730713, 2.5899994373321533, 2.729999542236328, 2.749999523162842, 2.8399994373321533], long_factor: [1.0800000429153442, 1.1100000143051147, 1.1399999856948853, 1.340000033378601, 1.5899999141693115, 1.600000023841858, 1.6200000047683716, 2.620000123977661, 3.2300000190734863, 3.2300000190734863, 4.789999961853027, 7.400000095367432, 7.700000286102295, 9.09000015258789, 12.199999809265137, 17.670000076293945, 24.46000099182129, 28.57000160217285, 30.420001983642575, 30.840002059936523, 32.590003967285156, 32.93000411987305, 42.32000350952149, 44.96000289916992, 50.34000396728515, 50.45000457763672, 57.55000305175781, 57.93000411987305, 58.21000289916992, 60.1400032043457, 62.61000442504883, 62.62000274658203, 62.71000289916992, 63.1400032043457, 63.1400032043457, 63.77000427246094, 63.93000411987305, 63.96000289916992, 63.970001220703125, 64.02999877929688, 64.06999969482422, 64.08000183105469, 64.12000274658203, 64.41000366210938, 64.4800033569336, 64.51000213623047, 64.52999877929688, 64.83999633789063], scaling_type: Su }), max_position_embeddings: 131072, use_flash_attn: false, sliding_window: Some(262144), original_max_position_embeddings: 4096, quantization_config: None, tie_word_embeddings: false }
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 128/128 [00:00<00:00, 3872.42it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 67/67 [00:00<00:00, 611111.11it/s]
2024-10-02T18:50:01.554183Z  INFO mistralrs_core::pipeline::isq: Loaded in-situ quantization artifacts into 129 total tensors. Took 0.27s
2024-10-02T18:50:01.588026Z  INFO mistralrs_core::pipeline::chat_template: bos_toks = "<s>", eos_toks = "<|endoftext|>", "<|end|>", "<|assistant|>", unk_tok = <unk>
2024-10-02T18:50:01.590672Z  INFO mistralrs_server: Model loaded.
2024-10-02T18:50:01.590745Z  INFO mistralrs_server::interactive_mode: Starting interactive loop with sampling params: SamplingParams { temperature: Some(0.1), top_k: Some(32), top_p: Some(0.1), min_p: Some(0.05), top_n_logprobs: 0, frequency_penalty: Some(0.1), presence_penalty: Some(0.1), stop_toks: None, max_len: Some(4096), logits_bias: None, n_choices: 1, dry_params: Some(DrySamplingParams { sequence_breakers: ["\n", ":", "\"", "*"], multiplier: 0.0, base: 1.75, allowed_length: 2 }) }
====================
Welcome to interactive mode! Because this model is a text model, you can enter prompts and chat with the model.

Commands:
- `\help`: Display this message.
- `\exit`: Quit interactive mode.
- `\system <system message here>`:
    Add a system message to the chat without running the model.
    Ex: `\system Always respond as a pirate.`
====================
> Hey
Hello! How can I assist you today?
>
```

**Comment by EricLBuehler** [comment]
@ChristianWeyer thank you for all the help testing! It looks like everything is working.

My Metal machine should arrive in 2 weeks - I'll begin work on improving Metal performance immediately.

**Pull request merged**
