### PR TITLE
Async channels

### PR DESCRIPTION
**Pull request by lucasavila00**
Closes https://github.com/EricLBuehler/mistral.rs/issues/235

### CODE REVIEW

**Comment by lucasavila00** [comment]
I tested the server, interactive mode, quantized example.

I think these cover all of the APIs?

**Comment by EricLBuehler** [comment]
@lucasavila00, thank you. Can you please test the Python bindings? It also seems like there are some more merge conflicts.

**Comment by lucasavila00** [comment]
@lucasavila00 I fixed the conflitcts and tested the python api.

**Comment by EricLBuehler** [comment]
@lucasavila00 thank you!

**Pull request merged**
