### PR TITLE
Handle assistant messages with 'tool_calls'

### PR DESCRIPTION
**Pull request by Jeadie**
## Changes
 - The core change here is 
 ```diff
-pub type MessageContent = Either<String, Vec<IndexMap<String, String>>>;
+pub type MessageContent = Either<String, Vec<IndexMap<String, Value>>>;
 ```

 - Also, change `BasicProcessor` to use `template_action() -> MessagesAction::Keep` (instead of `MessagesAction::FlattenOnlyText`) . 

### Fixes
 - #793

### CODE REVIEW

**Review by EricLBuehler — CHANGES_REQUESTED** [review]
Hi @Jeadie! Thanks for the PR. I think this looks good, but I was wondering if you could also please update the new Rust API (specifically, the `tools` and `tools_llama_8b` examples)? Perhaps you could create a method to add a tool call message?

Please let me know!

**Comment by EricLBuehler** [comment]
Friendly ping @Jeadie

**Comment by Jeadie** [comment]
Will do today

**Comment by Jeadie** [comment]
I don't seem to have visibility into the failing check: https://github.com/EricLBuehler/mistral.rs/actions/runs/11357273044/job/31589861979?pr=824

**Comment by EricLBuehler** [comment]
@Jeadie I reran the check and it passed. Please let me know when this is ready for review!

**Comment by Jeadie** [comment]
This is ready to review

**Review by EricLBuehler — APPROVED** [review]
Thank you!

**Comment by EricLBuehler** [comment]
@Jeadie I noticed there are some outstanding merge conflicts, could you please resolve those? Thanks.

**Comment by Jeadie** [comment]
@EricLBuehler Updated, thanks.

**Comment by EricLBuehler** [comment]
Thank you!

**Pull request merged**
