### PR TITLE
Async channels

### PR DESCRIPTION
**Pull request by lucasavila00**

### CODE REVIEW

**Comment by EricLBuehler** [comment]
@lucasavila00, I think there are merge conflicts here.

**Comment by lucasavila00** [comment]
@EricLBuehler fixed

**Comment by EricLBuehler** [comment]
@lucasavila00, does this require #198?

**Comment by lucasavila00** [comment]
@EricLBuehler it doesn't, they independent but will likely conflict

**Comment by EricLBuehler** [comment]
@lucasavila00, OK, I'll merge this first. Does this fix the problem of blocking in the axum handler?

**Comment by lucasavila00** [comment]
@EricLBuehler yes, it does fix the blocking in axum

**Comment by EricLBuehler** [comment]
@lucasavila00 great! It looks like CI is reporting some issues in the examples: https://github.com/EricLBuehler/mistral.rs/actions/runs/8864007524/job/24338802361?pr=228

**Comment by lucasavila00** [comment]
I'll re-create this MR

Fixing conflicts is showing to be harder than the initial implementation

**Comment by EricLBuehler** [comment]
Ok, sorry about that. Looking forward to it!

**Comment by lucasavila00** [comment]
@EricLBuehler np, this MR took a couple of minutes to write

**Pull request closed without merging**
