### PR TITLE
fix Half-Quadratic Quantization and Dequantization on CPU

### PR DESCRIPTION
**Pull request by haricot**
This confirms that `test_bitpack` is running solely on non-CPU hardware. To address this, we could implement a fix by ensuring contiguous data slices.

### CODE REVIEW

**Review by EricLBuehler — CHANGES_REQUESTED** [review]
Hi @haricot! Thanks for the PR. Can you please update it so it also tests 8 bit quantization? Thanks!

**Comment by EricLBuehler** [comment]
@haricot were you planning on implementing HQQ for non-CUDA devices in this PR? The name seems to indicate so, I was just wondering!

**Comment by haricot** [comment]
Indeed the title is not correct. It is rather: fix Half-Quadratic Quantization and Dequantization on CPU, because I am not sure I can optimize it.
My first goal was to make the quantization work on my device. In fact, I could not quantize the models, I got OOM.

With your models quantized on GPU and 8 VRAM, it worked correctly with this command:
`cargo run -r --features cuda -- --pa-gpu-mem-usage 0.5 -i plain -m '/path/' --from-uqff /model/llm-hqq4.uqff
`

With the model quantized on CPU, the inferences on CPU or GPU, I got inconsistent texts. After correct it , I realized that the inferences on CPU with the quantized models were not optimal. I tried to profile to see which step should be optimized and implement a SIMD version of the dequantize function but it didn't turn out to be enough, it seems necessary to add data alignment with SIMD.
I wonder if it is only about optimizing the dequantize function or adding a KV cache aligned system or something else?

About Half-Quadratic Quantization on GPU and possible offload CPU to avoid OOM:
I would like also to propose a method when a max limit of available VRAM is reached, the tensor is quantized on CPU. This is relevant?

**Review by EricLBuehler — APPROVED** [review]
Hi @haricot! All tests pass on CPU (the target of this PR) and the changes look good. Merging now, thanks for the contribution.

**Pull request merged**
